### PR TITLE
Serve public files from root instead of /pj and /pj/static

### PR DESCRIPTION
**Pull request by nickfarrow**
Moves nolooking website from `/pj` to `/`, while keeping the payjoin POST `/pj` and other endpoints the same.

### CODE REVIEW

**Review by 0xBEEFCAF3 — APPROVED** [review]
Nice!

**Comment by DanGould** [comment]
I understand the what,  but why?

**Comment by nickfarrow** [comment]
I keep getting caught out using the wrong paths for static files, (all the favicon paths had to be prefixed). On umbrel it'd be nice to be able to open up using IP:port, rather than see an error. Unless there's a reason to use `/pj`?

Even further, would it be possible to get rid of the `/static/` too and just host out of `/`?

**Comment by 0xBEEFCAF3** [comment]
Keeping the home page on / makes the most sense unless we plan to add a different homepage

In the future we can prefix our API paths too:  `api/some_version/`

**Comment by DanGould** [comment]
Oh yeah, this is crazy. The folder should really be called `/public` now too since we generate qr_codes into it. It's not only static files

**Comment by DanGould** [comment]
> Even further, would it be possible to get rid of the /static/ too and just host out of /?

This does that now

**Comment by nickfarrow** [comment]
tACK

**Pull request merged**
